export const items = [
  {
    productName: "SK SHANGHAI with CHILLI GARLIC",
    packaging: "40pcs/pack with Sauce",
    srp: 329,
    distributorPrice: 279.65,
  },
  {
    productName: "SK JAPANESE with CHILLI GARLIC",
    packaging: "40pcs/pack with Sauce",
    srp: 369,
    distributorPrice: 313.65,
  },
  {
    productName: "SK HONGKONG with CHILLI GARLIC",
    packaging: "40pcs/pack with Sauce",
    srp: 339,
    distributorPrice: 288.15,
  },
  {
    productName: "SK CHICKEN with CHILLI GARLIC",
    packaging: "40pcs/pack with Sauce",
    srp: 298,
    distributorPrice: 253.3,
  },
  {
    productName: "SPK COMBI SIOPAO with SAUCE",
    packaging: "6pcs/pack",
    srp: 180,
    distributorPrice: 153,
  },
  {
    productName: "SPK CHILLI ASADO SIOPAO with SAUCE",
    packaging: "6pcs/pack",
    srp: 190,
    distributorPrice: 161.5,
  },
  {
    productName: "SPK CHICKEN SIOPAO with SAUCE",
    packaging: "6pcs/pack",
    srp: 158,
    distributorPrice: 134.3,
  },
  {
    productName: "SPK BOLA BOLA SIOPAO with SAUCE",
    packaging: "6pcs/pack",
    srp: 180,
    distributorPrice: 153,
  },
  {
    productName: "SPK ASADO SIOPAO with SAUCE",
    packaging: "6pcs/pack",
    srp: 190,
    distributorPrice: 161.5,
  },
  {
    productName: "NH BEEF TERIYAKI",
    packaging: "+-800gms/pack",
    srp: 398,
    distributorPrice: 278.6,
  },
  {
    productName: "NH WANTON with CHILLI GARLIC",
    packaging: "30pcs/pack with Sauce",
    srp: 340,
    distributorPrice: 289,
  },
  {
    productName: "NH DUMPLING with CHILLI GARLIC",
    packaging: "25pcs/pack with Sauce",
    srp: 320,
    distributorPrice: 272,
  },
  {
    productName: "NH PORK SIOMAI with CHILLI GARLIC",
    packaging: "35pcs/pack with Sauce",
    srp: 358,
    distributorPrice: 304.3,
  },
  {
    productName: "NH BEEF SIOMAI with CHILLI GARLIC",
    packaging: "35pcs/pack with Sauce",
    srp: 340,
    distributorPrice: 289,
  },
  {
    productName: "NH PEANUT SAUCE PACK",
    packaging: "100gms/pack",
    srp: 71,
    distributorPrice: 49.7,
  },
  {
    productName: "NH TERIYAKI SAUCE PACK",
    packaging: "100gms/pack",
    srp: 77,
    distributorPrice: 53.9,
  },
  {
    productName: "NH OYSTER SAUCE PACK",
    packaging: "100gms/pack",
    srp: 52.5,
    distributorPrice: 36.75,
  },
  {
    productName: "EGG NOODLES PACK",
    packaging: "720gms/pack",
    srp: 227.5,
    distributorPrice: 159.25,
  },
  {
    productName: "PK CLASSIC CHIPS PACK",
    packaging: "1kg/pack",
    srp: 358.75,
    distributorPrice: 304.94,
  },
  {
    productName: "PK CLASSIC FRIES PACK",
    packaging: "1kg/pack",
    srp: 210,
    distributorPrice: 178.5,
  },
  {
    productName: "PK SKINNY FRIES PACK",
    packaging: "1kg/pack",
    srp: 341.25,
    distributorPrice: 290.06,
  },
  {
    productName: "PK CHEESE POWDER PACK",
    packaging: "60gms/pack",
    srp: 175,
    distributorPrice: 148.75,
  },
  {
    productName: "PK BBQ POWDER PACK",
    packaging: "60gms/pack",
    srp: 175,
    distributorPrice: 148.75,
  },
  {
    productName: "PK SOUR CREAM POWDER PACK",
    packaging: "60gms/pack",
    srp: 175,
    distributorPrice: 148.75,
  },
  {
    productName: "GULAMAN POWDER",
    packaging: "370gms/pack",
    srp: 122.5,
    distributorPrice: 85.75,
  },
  {
    productName: "BURGER PATTY PACK",
    packaging: "10patties/pack",
    srp: 122,
    distributorPrice: 85.4,
  },
  {
    productName: "SIOPAO SAUCE",
    packaging: "",
    srp: 2,
    distributorPrice: 1.5,
  },
  {
    productName: "CHILLI GARLIC SAUCE",
    packaging: "20gms/pack",
    srp: 18,
    distributorPrice: 15,
  },
  {
    productName: "BOY BONDAT PARES SAUCE",
    packaging: "",
    srp: 45,
    distributorPrice: 38.25,
  },
  {
    productName: "BOY BONDAT BEEF PARES W/CHILI",
    packaging: "140gms/pack",
    srp: 182,
    distributorPrice: 154.7,
  },
  {
    productName: "BOY BONDAT REGULAR SISIG",
    packaging: "100gms/pack",
    srp: 160,
    distributorPrice: 136,
  },
  {
    productName: "BOY BONDAT SPICY SISIG",
    packaging: "100gms/pack",
    srp: 160,
    distributorPrice: 136,
  },
  {
    productName: "BOY BONDAT BEEF PARES W/CHILI FAMILY TRAY 450g",
    packaging: "In Tray 450gms/pack",
    srp: 362,
    distributorPrice: 325.8,
  },
  {
    productName: "BOY BONDAT REGULAR SISIG FAMILY TRAY 300g",
    packaging: "In Tray 300gms/pack",
    srp: 358,
    distributorPrice: 322.2,
  },
  {
    productName: "BOY BONDAT SPICY SISIG FAMILY TRAY 300g",
    packaging: "In Tray 300gms/pack",
    srp: 358,
    distributorPrice: 322.2,
  },
  {
    productName: "BOY BONDAT KARE-KARE TRAY 450g",
    packaging: "In Tray 450gms/pack",
    srp: 366,
    distributorPrice: 329.4,
  },
  {
    productName: "BOY BONDAT GOTO TRAY 500g",
    packaging: "In Tray 500gms/pack",
    srp: 298,
    distributorPrice: 268.2,
  },
  {
    productName: "CHICKEN BUCHERON",
    packaging: "60gms/pack (10pcs)",
    srp: 108,
    distributorPrice: 97.2,
  },
  {
    productName: "MARINATED CHICKEN DRUMSTIC TRAY w/ SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 168,
    distributorPrice: 151.2,
  },
  {
    productName: "MARINATED CHICKEN THIGH TRAY w/ SAUCE 500G",
    packaging: "In Tray 500gms/pack",
    srp: 168,
    distributorPrice: 151.2,
  },
  {
    productName: "MARINATED CHICKEN LEG QUARTER TRAY w/ SAUCE 350g",
    packaging: "In Tray 350gms/pack",
    srp: 128,
    distributorPrice: 115.2,
  },
  {
    productName: "MARINATED CHICKEN NECK TRAY w/ SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 118,
    distributorPrice: 106.2,
  },
  {
    productName: "MARINATED CHICKEN CUT-UPS TRAY w/ SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 158,
    distributorPrice: 142.2,
  },
  {
    productName: "MARINATED PORK LIEMPO TRAY w/ SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 278,
    distributorPrice: 250.2,
  },
  {
    productName: "MARINATED PORK LIEMPO  BITES TRAY W/SAUCE 500G",
    packaging: "In Tray 500gms/pack",
    srp: 268,
    distributorPrice: 241.2,
  },
  {
    productName: "MARINATED SPICY CHICKEN NECK TRAY WITH SAUCE  500g",
    packaging: "In Tray 500gms/pack",
    srp: 128,
    distributorPrice: 115.2,
  },
  {
    productName: "MARINATED SPICY CHICKEN CUT-UPS TRAY WITH SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 178,
    distributorPrice: 160.2,
  },
  {
    productName: "MARINATED SPICY PORK LIEMPO CHOPS WITH SAUCE 500g",
    packaging: "In Tray 500gms/pack",
    srp: 288,
    distributorPrice: 259.2,
  },
  {
    productName: "SK EXPRESS BEEF NOODLES",
    packaging: "450gms/pack",
    srp: 278,
    distributorPrice: 250.2,
  },
  {
    productName: "SK EXPRESS KUCHAI DUMPLINGS",
    packaging: "30pcs/pack",
    srp: 262,
    distributorPrice: 235.8,
  },
  {
    productName: "SK EXPRESS PORK DUMPLINGS",
    packaging: "30pcs/pack",
    srp: 256,
    distributorPrice: 230.4,
  },
  {
    productName: "SK EXPRESS PORK GYOZA",
    packaging: "12pcs/pack",
    srp: 206,
    distributorPrice: 185.4,
  },
  {
    productName: "SK EXPRESS SPICY CHICKEN",
    packaging: "300gms/pack",
    srp: 217,
    distributorPrice: 195.3,
  },
  {
    productName: "SK EXPRESS SPICY PORK",
    packaging: "300gms/pack",
    srp: 234,
    distributorPrice: 210.6,
  },
  {
    productName: "SK EXPRESS SPICY SQUID",
    packaging: "300gms/pack",
    srp: 223,
    distributorPrice: 200.7,
  },
  {
    productName: "SK EXPRESS TAIWAN ASADO SIOPAO",
    packaging: "6pcs/pack",
    srp: 240,
    distributorPrice: 216,
  },
  {
    productName: "SK EXPRESS TAIWAN BOLA BOLA  SIOPAO",
    packaging: "6pcs/pack",
    srp: 240,
    distributorPrice: 216,
  },
  {
    productName: "SK EXPRESS TAIWAN MANTHOU (BROWN)",
    packaging: "9pcs/pack",
    srp: 90,
    distributorPrice: 81,
  },
  {
    productName: "SK EXPRESS TAIWAN MANTHOU (CLASSIC)",
    packaging: "9pcs/pack",
    srp: 90,
    distributorPrice: 81,
  },
  {
    productName: "SK EXPRESS TAIWAN MANTHOU (UBE)",
    packaging: "9pcs/pack",
    srp: 90,
    distributorPrice: 81,
  },
  {
    productName: "SK EXPRESS TAIWAN MANTHOU (WHEAT)",
    packaging: "9pcs/pack",
    srp: 90,
    distributorPrice: 81,
  },
  {
    productName: "SK SHANGHAI with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 170,
    distributorPrice: 144.5,
  },
  {
    productName: "SK JAPANESE with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 198,
    distributorPrice: 168.3,
  },
  {
    productName: "SK HONGKONG with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 180,
    distributorPrice: 153,
  },
  {
    productName: "SK CHICKEN with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 159,
    distributorPrice: 135.15,
  },
  {
    productName: "NH WANTON with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 198,
    distributorPrice: 168.3,
  },
  {
    productName: "NH DUMPLING with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 189,
    distributorPrice: 160.65,
  },
  {
    productName: "NH PORK SIOMAI with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 189,
    distributorPrice: 160.65,
  },
  {
    productName: "NH BEEF SIOMAI with CHILLI GARLIC (APPROX 260G)",
    packaging: "20pcs/Tray",
    srp: 170,
    distributorPrice: 144.5,
  },
  {
    productName:
      "JC X KATUNYING BUNDLE OF SWEETS (brownies, b-scotch,choco marble)",
    packaging: "12PCS/Box",
    srp: 406,
    distributorPrice: 365.4,
  },
];
